---
# https://pre-commit.com/
default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bun run lint:fix
        language: system
        pass_filenames: false
      - id: typescript
        name: type check
        entry: bun run type:check
        language: system
        types_or: [ts, tsx]
        pass_filenames: false
      - id: package
        name: package validate
        entry: bun run vsce package -o /tmp/test.vsix
        language: system
        pass_filenames: false
        types_or: [ts, tsx, json]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: remove-tabs
        args: [--whitespaces-count, '2']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
        # Some .json files contain useful comments, they shall not be removed
        exclude: ^(.*tsconfig.*\.json|\.vscode/.*\.json)$
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.46.2
    hooks:
      - id: typos
        args: [--format, brief, --write-changes, --force-exclude]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
      - id: htmlhint
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.14.2
    hooks:
      - id: markdown-link-check
        name: markdown link check
        args: [--quiet, --alive, '200,429']
        exclude: ^CHANGELOG\.md$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        args: [--fix]
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.19.1
    hooks:
      - id: yamlfix
        entry: env YAMLFIX_WHITELINES=1 YAMLFIX_SECTION_WHITELINES=1 yamlfix
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.46.2
    hooks:
      - id: typos
        name: detect typos in commit message
        args: [--format, brief]
        stages: [commit-msg]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        additional_dependencies:
          - github.com/wasilibs/go-shellcheck/cmd/shellcheck@latest
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: [--ignore, body-is-missing, --msg-filename]
        stages: [commit-msg]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
